# https://taskfile.dev/usage/
version: "3"
vars:
  DEV_API_HOST: http://localhost:4000
  FLY_API_HOST: https://slink.fly.dev
  LOCAL_MAGIC_COOKIE: slink
  DOCKER_IMG_NAME: slink
  DOCKER_CONTAINER_NAME: slink
includes:
  # task f:iex
  flyio:
    taskfile: ./Taskfile-flyio.yml
    aliases: [f, fly]
    optional: true
tasks:
  default: mix test
  sh: iex --erl "-kernel shell_history enabled" -S mix
  drun: |
    mix deps.compile phoenix phoenix_live_view
    task run
  run:
    env:
      ERL_AFLAGS: "-kernel shell_history enabled"
    cmds:
      # - iex --erl "-kernel shell_history enabled" -S mix phx.server
      - iex -S mix phx.server
  run6:
    aliases: [r6, n6, node6]
    env:
      # local livebook deployed with ipv6
      ERL_AFLAGS: "-proto_dist inet6_tcp -kernel shell_history enabled"
      # RELEASE_DISTRIBUTION: name
    cmds:
      # iex(slink@mac.local)1>
      - iex --name slink --cookie slink -S mix phx.server
  fmt: mix format

  reset:
    aliases: [r]
    cmds:
      - |
        mix reset
        mix test.reset
  clean.links: find deps/ -type l -depth 1 -delete

  ## assets install or upgrade
  bun.install: mix bun assets install --verbose
  bun.ls: mix bun assets pm ls

  scc: |
    # brew install scc
    scc --exclude-dir _local,.elixir_ls,_build,deps,node_modules --include-ext ex,exs,eex,heex,js .

  ## AI
  td: |
    # curl -v http://localhost:4000/tidewave/mcp
    echo '{"jsonrpc":"2.0","id":1,"method":"ping"}' | /Users/rj/dev/elab/mcp-proxy http://localhost:4000/tidewave/mcp # --debug

  ## Links
  link.create: |
    curl -X POST \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer dev_api_token---kC6IkpcQRO4VvuVFgszZRnvDDSU" \
      -d '{"link": {"title": "Example", "url": "https://example1.com"}}' \
      {{.DEV_API_HOST}}/api/links

  ## DB ops
  db:
    aliases: [sql, pg]
    cmds:
      - pgcli slink_dev
  db.reset: |
    mix do dev.reset + test.reset
  db.mig: mix ecto.migrate
  # task db.back -- 1
  db.back: mix ecto.rollback --step {{.CLI_ARGS}}
  db.back1: task db.back -- 1
  db.fly.local: |
    mix dev.db.init
    mix run run/fly-db-local-restore.exs
    mix ecto.migrate
    mix run run/dev/seed.exs
  db.fly.dump: |
    mix run run/fly-db-dump.exs
  # db browser tool: beekeeper

  ## Git ops https://github.com/zachdaniel/git_ops/blob/master/CHANGELOG.md
  ops: mix git_ops.project_info
  ops.up: |
    mix git_ops.release --yes
    git push --follow-tags
    # fly deploy
  ops.up.rel: mix git_ops.release
  ops.up.tag: git push --follow-tags
  ops.types: mix eh.git.ops.types
  ops.init: mix git_ops.release --initial
  ops.setup: |
    # run after add igniter dep in mix.exs
    mix igniter.install git_ops

  ## Remote Ops with WireGuard opened
  # https://fly.io/docs/elixir/advanced-guides/clustering-from-home-to-your-app-in-fly/
  # CLUSTER_APP_NAME=xxx task remote.connect6
  remote.connect6:
    aliases:
      - remote.s2
      - rc6
    env:
      ERL_AFLAGS: "-kernel shell_history enabled"
      CLUSTER_APP_NAME: "slink"
      RELEASE_COOKIE: happy-cookie-not-secret-but-for-cluster
    cmds:
      - |
        echo "==Custerning into remote app ${CLUSTER_APP_NAME}"
        echo "Trigger slink running if suspended"
        curl {{.FLY_API_HOST}}/api | jq
      - run/cluster-with-remote.sh

  # https://fly.io/docs/elixir/advanced-guides/connect-observer-to-your-app/
  # NOTE:
  # - If everything worked and it’s connected, under the Nodes menu you should see the connected remote node.
  # - live-dashboard is better way!
  observer:
    aliases:
      - observe
    env:
      COOKIE: happy-cookie-not-secret-but-for-cluster
    cmds:
      - echo "==Observing remote app"
      - run/observer.sh

  # local release run in dev mode
  prel: MIX_ENV=prod mix release --overwrite
  lp-test:
    dir: local-prod
    cmds:
      - pwd
  lp: task lp-stop && task lp-run -- daemon
  lp-run:
    dir: local-prod
    cmds:
      - run/prod.sh
  lp-stop:
    dir: local-prod
    cmds:
      - _build/dev/rel/slink/bin/slink stop
  lps: task lp-stop && task lp-run -- start

  ## Docker run env
  dk.build: docker build -t {{.DOCKER_IMG_NAME}} .
  # dk.run: |
  #   task dk.build
  #   docker rm -f {{.DOCKER_CONTAINER_NAME}}
  #   docker run --name {{.DOCKER_CONTAINER_NAME}} --rm -it -p 4010:4000 \
  #     -e "PHX_SERVER=true" \
  #     -e "SECRET_KEY_BASE=mock-test-secret-key-base" \
  #     -e "RELEASE_DISTRIBUTION=name" \
  #     -e "RELEASE_NODE=slink@{{.DOCKER_CONTAINER_NAME}}.orb.local" \
  #     -e "RELEASE_COOKIE={{.LOCAL_MAGIC_COOKIE}}" \
  #     {{.DOCKER_IMG_NAME}} bin/slink start_iex
  dk.iex: docker exec -it {{.DOCKER_CONTAINER_NAME}} bin/slink remote
  dk.in: docker exec -it {{.DOCKER_CONTAINER_NAME}} sh
  dk.sh: docker run --rm -it {{.DOCKER_IMG_NAME}} sh
  dk.info: |
    docker exec -it {{.DOCKER_CONTAINER_NAME}} bin/slink
  dk.ping: curl https://{{.DOCKER_CONTAINER_NAME}}.orb.local/ping | jq
  dk.down: docker stop {{.DOCKER_CONTAINER_NAME}}
  dk.test: |
    docker compose version
    docker compose up --quiet-pull --exit-code-from curl # --abort-on-container-exit
