defmodule SlinkWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :slink

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_slink_key",
    signing_salt: "MtbIihgV",
    same_site: "Lax"
  ]

  ## Sockets

  # https://github.com/phoenixframework/phoenix_live_view/blob/v1.1.18/lib/phoenix_live_view/socket.ex#L105
  socket "/live", Phoenix.LiveView.Socket,
    # longpoll: [
    #   connect_info: [session: @session_options],
    #   transport_log: :debug
    # ],
    longpool: false,
    websocket: [
      connect_info: [session: @session_options],
      transport_log: :debug
    ]

  ## Try channel and sockets
  # - https://hexdocs.pm/phoenix/1.8.1/channels.html#tying-it-all-together
  # - https://hexdocs.pm/phoenix/1.8.1/Phoenix.Endpoint.html#socket/3
  socket "/ws/chat", SlinkWeb.ChatSocket,
    # websocket: true,
    websocket: [
      # https://hexdocs.pm/phoenix/1.8.1/Phoenix.Endpoint.html#socket/3-connect-info
      connect_info: [
        # In order to validate the session, the "_csrf_token" must be given as request parameter
        # when connecting the socket with the value of URI.encode_www_form(Plug.CSRFProtection.get_csrf_token())
        # ref assets/js/chat_socket.js
        session: @session_options
      ],
      transport_log: :debug,
      error_handler: {SlinkWeb.ChatSocket, :handle_error, []}
    ],
    # longpoll: false,
    auth_token: false

  # https://hexdocs.pm/phoenix/1.8.1/Phoenix.Endpoint.html#socket/3
  socket "/ws/echo", SlinkWeb.EchoSocket,
    # longpoll: false, # this is default
    # websocket: true, # default is true
    websocket: [
      # access ws endpoint at: ws://localhost:4000/ws/echo/websocket
      # path: "/websocket",
      # connect_info: [
      #   session: @session_options
      # ],
      transport_log: :debug
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :slink,
    gzip: not code_reloading?,
    only: SlinkWeb.static_paths()

  if Code.ensure_loaded?(Tidewave) do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :slink
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug SlinkWeb.Router
end
